language: php

sudo: false

php:
    - 7.0

env:
    - WP_VERSION=4.5 WP_MULTISITE=0

matrix:
  include:
    - php: 7.1
      env: WP_VERSION=trunk

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
      composer global require "phpunit/phpunit=5.7.*"
    else
      composer global require "phpunit/phpunit=4.8.*"
    fi
script: phpunit